version: '3.8'
services: 
    nodejs:
        image: jelastic/nodejs
        container_name: webapi
        env_file: .env
        ports: 
            - "8080:3008"
        volumes:
            - .:/home/node/app
            - ./node_modules:/home/node/app/node_modules
        command: node /home/node/app/server.js
        environment:
            SECRET_AUTH_TOKEN: DFSHDFFHSDQFJDSQHD85345843H54354
            DB_AUTH_URL: 'mongodb+srv://saliou:salioutester2018@cluster0.et7lj.mongodb.net/gdp-manager?retryWrites: true&w: majority'
            DB_MYSQL_HOST: '141.136.43.1'
            DB_MYSQL_NAME: u581471203_Ehpad
            DB_MYSQL_PWD: Loco2laurent!
            DB_MYSQL_USER: u581471203_contact
