version: '3.8'
services:
    db:
        image : mongo
        container_name: gdpcm_db
        networks:
            - mongodb_network
        env_file: .env
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - /usr/database:/data/db
        ports: 
        - 27017:27017
        restart: unless-stopped
    api:
        build: .
        depends_on: 
            - db
        restart: unless-stopped
        container_name: gdpcm_api
        networks:
            - mongodb_network
        env_file: .env
        ports: 
            - "3008:3008"
networks:
    mongodb_network:
        name: mongodb_network
                
